"""add chunking configuration to generations

Records which chunking configuration built a generation's chunks (§18.10), and
makes re-chunking an unchanged document a recorded no-op.

The second part is the point. Generations are per document version, so changing
one filing never re-embeds the corpus — but re-running chunking on an unchanged
version with an unchanged configuration produced a *second* generation and
re-embedded every chunk. Measured at roughly 105 seconds for a 1,300-chunk filing,
for a byte-identical result.

Extraction already solved this with a partial unique index on
(document_version_id, producer_policy, config_version). This is the same shape,
keyed on the chunking configuration, and it excludes failed generations for the
same reason: a failure must stay retryable.

The column is nullable because a generation exists before its chunking component
completes. A generation is a container that fills (§11.12), not a row written once
at the end.

Revision ID: 09e6b5dcbabf
Revises: fd1ef306a169
Create Date: 2026-10-04 18:05:40.615844+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '09e6b5dcbabf'
down_revision: str | None = 'fd1ef306a169'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('chunking_config_version', sa.String(length=32), nullable=True))
    op.create_index('uq_generations_configuration', 'generations', ['document_version_id', 'extraction_run_id', 'chunking_config_version'], unique=True, postgresql_where=sa.text("state <> 'failed'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_generations_configuration', table_name='generations', postgresql_where=sa.text("state <> 'failed'"))
    op.drop_column('generations', 'chunking_config_version')
    # ### end Alembic commands ###
