"""create chunks

The retrieval representation (§14.2) and the events that index it. Three tables
that are written in one transaction and are meaningless apart.

chunks holds the text search looks at. It is not evidence — §14.1 keeps that with
the source representation — so chunk_sources records which source regions each
chunk was built from (§14.7). A chunk that cannot name its sources cannot be
cited, and §14.9 makes a citation resolving to nothing worse than no answer. That
relation is a table rather than an array because it is traversed from both ends:
"which blocks back this chunk?" and, for the Evidence Gate, "which chunks cite
this block?"

index_outbox is §29.8 — chunk and index-event records commit together. Writing
chunks and then calling an embedding model would either hold a transaction across
a network call, which §29.7 forbids, or risk committing chunks that are never
indexed and so never retrievable while looking identical to indexed ones.

The lexemes column is written by the application, not generated by the database. A
generated column would require the text-search configuration as a literal in the
schema, and §9.7 reserves that choice for recorded evidence "when the lexical index
is built, not assumed when it is first written". Changing it is therefore a
re-chunk under a new generation (§18.11), not a migration.

Two constraints worth reading twice. char_count_matches_text has the database
recompute the length rather than trust the application, as source_elements already
does, because a count that disagrees with its text corrupts every budget decision
built on it. only_a_child_has_a_parent refuses a parent pointing at a parent: that
builds a cycle §20.8's context expansion would follow forever.

Revision ID: fd1ef306a169
Revises: c9d2a8b45e71
Create Date: 2026-10-04 13:35:29.467806+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'fd1ef306a169'
down_revision: str | None = 'c9d2a8b45e71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lexemes', postgresql.TSVECTOR(), nullable=True),
    sa.Column('heading_path', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('page_numbers', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('narrative', 'table_derived')", name=op.f('ck_chunks_evidence_type_known')),
    sa.CheckConstraint("parent_id IS NULL OR role = 'child'", name=op.f('ck_chunks_only_a_child_has_a_parent')),
    sa.CheckConstraint("role IN ('child', 'parent')", name=op.f('ck_chunks_role_known')),
    sa.CheckConstraint('array_position(heading_path, NULL) IS NULL', name=op.f('ck_chunks_heading_path_has_no_nulls')),
    sa.CheckConstraint('char_count = char_length(text)', name=op.f('ck_chunks_char_count_matches_text')),
    sa.CheckConstraint('length(text) > 0', name=op.f('ck_chunks_text_not_blank')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_chunks_ordinal_non_negative')),
    sa.CheckConstraint('token_count >= 0', name=op.f('ck_chunks_token_count_non_negative')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_chunks_document_version_id_document_versions')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_chunks_generation_id_generations')),
    sa.ForeignKeyConstraint(['parent_id'], ['chunks.id'], name=op.f('fk_chunks_parent_id_chunks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_document_version_id'), 'chunks', ['document_version_id'], unique=False)
    op.create_index('ix_chunks_generation_id', 'chunks', ['generation_id', 'ordinal'], unique=False)
    op.create_index('ix_chunks_lexemes', 'chunks', ['lexemes'], unique=False, postgresql_using='gin')
    op.create_table('chunk_sources',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('source_element_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_chunk_sources_position_non_negative')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_chunk_sources_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['source_element_id'], ['source_elements.id'], name=op.f('fk_chunk_sources_source_element_id_source_elements')),
    sa.PrimaryKeyConstraint('chunk_id', 'source_element_id', name=op.f('pk_chunk_sources'))
    )
    op.create_index('ix_chunk_sources_source_element_id', 'chunk_sources', ['source_element_id'], unique=False)
    op.create_table('index_outbox',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(state = 'pending') = (completed_at IS NULL)", name=op.f('ck_index_outbox_completed_at_matches_state')),
    sa.CheckConstraint("state IN ('pending', 'completed', 'failed')", name=op.f('ck_index_outbox_state_known')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_index_outbox_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_index_outbox_generation_id_generations')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_index_outbox'))
    )
    op.create_index('ix_index_outbox_pending', 'index_outbox', ['generation_id'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_outbox_pending', table_name='index_outbox', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('index_outbox')
    op.drop_index('ix_chunk_sources_source_element_id', table_name='chunk_sources')
    op.drop_table('chunk_sources')
    op.drop_index('ix_chunks_lexemes', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_generation_id', table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_version_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
